pipeline {
    agent any
    stages {
        
        stage('Staging'){
            steps{
                echo 'Starting staging job'
                build job: 'PIPELINE-FULL-STAGING', parameters: [
                      string(name:'ENVIRONMENT', value: "staging")]
            }
        }
        stage('Merge'){
            steps{
                script {
                    withCredentials([sshUserPrivateKey(credentialsId: 'sshGitHub', keyFileVariable: '')]) {
                        sh script: """
                            set -x
                            git branch -a
                            git checkout -b develop origin/develop
                            git checkout -b master origin/master
                            git merge develop
                            git remote set-url origin https://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@github.com/BernardoJoseLlamasVerna/todo-list-aws.git
                            git config --global user.name "BernardoJoseLlamasVerna"
                            git push origin master
                        """, label: "Merging code to master"
                    }
                }

            }
        }
        stage('Production'){
            steps{
                
                echo 'Starting production job'
                build job: 'PIPELINE-FULL-PRODUCTION', parameters: [
                      string(name:'ENVIRONMENT', value: "production")]
            }
        }
    }
    post { 
        always { 
            echo 'Clean env: delete dir'
            cleanWs()
        }
    }
}
